### ISSUE TITLE
Validate

### ISSUE THREAD

**Issue by mirecl** [kerim-gorn/deposit-api#2]
Ошибка валидации при входных данных:
```json
{
   'amount': 1005000,
   'date': '01.01.2022', 
   'periods': 5, 
   'rate': 1.0
}
```

Ответ от Сервиса:
```json
{
   error': 'Invalid amount value'
}
```

Сумма `1 005 000` - **валидная** (см. задание).

**Comment by kerim-gorn** [comment]
Допустимые значения параметра amount были [10000, 1000000] и исправлены на [10000, 3000000]. Ошибка допущена ввиду низкого качества изображения с заданием.

**Comment by mirecl** [comment]
Перешли плиз письмо с заданием на `grazhdankov@gmail.com`.

**Comment by kerim-gorn** [comment]
Переслал.

**Comment by mirecl** [comment]
Ошибка **валидации** не исправилась.

**Comment by kerim-gorn** [comment]
Внесена дополнительная правка.
