### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by mirecl** [kerim-gorn/deposit-api#3]
Привести код к `PEP8` (Style Guide for Python Code).

**Comment by kerim-gorn** [comment]
Код приведен к PEP8.

**Comment by mirecl** [comment]
Большая просьба отказаться от новой функции `python 3.10` pattern matching + посмотреть файл с тестами на соответствие PEP8.

**Comment by kerim-gorn** [comment]
Pattern matching убран. Скорректировал code style в конструкции вызова функции `calculate_deposit`. Подскажи, пожалуйста, допустимо ли текущее оформление вложенности словарей?

**Comment by mirecl** [comment]
Для проверки кода можно воспользоваться `flake8`.
```bash
flake8 --version     
4.0.1 (black: 0.2.3, flake8-bugbear: 21.9.2, flake8-docstrings: 1.6.0, pydocstyle: 6.1.1, mccabe: 0.6.1, naming: 0.12.1, pycodestyle:
2.8.0, pyflakes: 2.4.0)
```

**Comment by kerim-gorn** [comment]
Произвел code style правки с применением flake8. Большое спасибо, не знал о таком удобном инструменте.

**Comment by mirecl** [comment]
flake8 **deposit_api.py**:
deposit_api.py:1:1: D210 No whitespaces allowed surrounding docstring text
deposit_api.py:1:1: D400 First line should end with a period
deposit_api.py:10:12: BLK100 Black would make changes.
deposit_api.py:11:1: D103 Missing docstring in public function
deposit_api.py:53:1: D210 No whitespaces allowed surrounding docstring text
deposit_api.py:53:1: D400 First line should end with a period

flake8 **test_deposit_api.py** 
test_deposit_api.py:1:1: D210 No whitespaces allowed surrounding docstring text
test_deposit_api.py:1:1: D400 First line should end with a period
test_deposit_api.py:11:1: D103 Missing docstring in public function
test_deposit_api.py:16:1: D103 Missing docstring in public function
test_deposit_api.py:17:23: BLK100 Black would make changes.

**Comment by kerim-gorn** [comment]
Правки произведены.
